package com.mytest.model.system;

import com.jfinal.plugin.activerecord.Page;
import com.mytest.model.base.system.BaseSystemIcon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemIcon extends BaseSystemIcon<SystemIcon> {
	public static final SystemIcon dao = new SystemIcon();
	private final String TABLENAME = "system_icon";
	
	public Page<SystemIcon> iconList(int page,int rows){
		return dao.paginate(page, rows, "select * ", " from " + TABLENAME);
	}
}