package com.api_projects.model.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjects<M extends BaseProjects<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTestUrl(java.lang.String testUrl) {
		set("test_url", testUrl);
	}

	public java.lang.String getTestUrl() {
		return get("test_url");
	}

	public void setRealUrl(java.lang.String realUrl) {
		set("real_url", realUrl);
	}

	public java.lang.String getRealUrl() {
		return get("real_url");
	}

	public void setShow(java.lang.Integer show) {
		set("show", show);
	}

	public java.lang.Integer getShow() {
		return get("show");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
