package com.api_projects.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApiInOut<M extends BaseApiInOut<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setApiId(java.lang.Integer apiId) {
		set("api_id", apiId);
	}

	public java.lang.Integer getApiId() {
		return get("api_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setGenre(java.lang.String genre) {
		set("genre", genre);
	}

	public java.lang.String getGenre() {
		return get("genre");
	}

	public void setRequest(java.lang.Integer request) {
		set("request", request);
	}

	public java.lang.Integer getRequest() {
		return get("request");
	}

	public void setNature(java.lang.Integer nature) {
		set("nature", nature);
	}

	public java.lang.Integer getNature() {
		return get("nature");
	}

}
