package com.mytest.model.web;

import com.mytest.model.base.web.BaseCategories;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Categories extends BaseCategories<Categories> {
	public static final Categories dao = new Categories();
}
