package com.mytest.model.web;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.mytest.model.base.web.BaseFiles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Files extends BaseFiles<Files> {
	public static final Files dao = new Files();
	private final String TABLENAME = "files";

	/**
	 * 根据uuid获取附件列表
	 * @param uuid
	 * @return
	 */
	public List<Files> getFiles(String uuid) {
		return dao.find("select * from " + TABLENAME + " as obj where obj.uuid=?", uuid);
	}
	
	/**
	 * 根据uuid删除附件
	 * @param uuid
	 */
	public void deleteByUUId(String uuid){
		Db.update("delete from " + TABLENAME + " where uuid=?",uuid);
	}
}