package com.mytest.model.web;

import com.mytest.model.base.web.BaseNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
	public static final News dao = new News();
}
