package com.api_projects.model;

import com.api_projects.model.base.BaseApiInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApiInfo extends BaseApiInfo<ApiInfo> {
	public static final ApiInfo dao = new ApiInfo();
}
