package com.api_projects.model;

import com.api_projects.model.base.BaseApiInOut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApiInOut extends BaseApiInOut<ApiInOut> {
	public static final ApiInOut dao = new ApiInOut();
}
