package com.api_projects.model;

import com.api_projects.model.base.BaseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Log extends BaseLog<Log> {
	public static final Log dao = new Log();
}
