package com.api_projects.model;

import com.api_projects.model.base.BaseProjects;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Projects extends BaseProjects<Projects> {
	public static final Projects dao = new Projects();
}
